defaults:
  - agent: sac


experiment: CoRe


# RRM learning
segment: 3 
activation: tanh
num_seed_steps: 1000
num_pre_steps: 19000
num_interact: 4000
RRM_lr: 0.0003
RRM_batch: 5 
RRM_update: 10
feed_type: 0
reset_update: 100
topK: 5
ensemble_size: 3
max_feedback: 500
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0
# scheduling
RRM_schedule: 0

# RRM model
resnet: 0 
image_size: 300
conv_kernel_sizes: [5, 3, 3, 3] 
conv_n_channels: [16, 32, 64, 128] 
conv_strides: [3, 2, 2, 2]
# use cached labels
cached_label_path: 


# training config
num_train_steps: 5e5
replay_buffer_capacity: 200000
# evaluation config
eval_frequency: 10000
num_eval_episodes: 10
save_eval_video: False
# setups
seed: 0
device: cuda


# logger
log_frequency: 10000
log_save_tb: true
use_wandb: False


# Environment
env: metaworld_drawer-open-v2
gradient_update: 1


# load pretrained models
reward_model_load_dir: None
reward_model_score_load_dir: None
agent_model_load_dir: None


# FRM config
FRM_align_step: 25000 
FRM_align_max_steps: 100000 # MAX steps for alignment
use_FRM_online: True
reward_alpha: 0.5

# hydra configuration
hydra:
    job:
        chdir: True
    run:
        dir: ./exp/${experiment}/${env}/inter${num_interact}_maxfeed${max_feedback}_seg${segment}_Rlr${RRM_lr}_Rbatch${RRM_batch}_Rupdate${RRM_update}/seed${seed}_${now:%Y-%m-%d}-${now:%H-%M-%S}
